---
- name: "Install Apache2"
  become: true
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: "copy index.html page"
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes
