- hosts: webserver
  user: ubuntu
  roles:
    - apache

  # tasks:
  #   - name: "isntalling and configuring Apache"
  #     shell: |
  #       yum update -y
  #       yum install -y httpd
  #       systemctl start httpd
  #     register: shell_output
  #     become: true
