version: 2.1

commands:
  create-stack:
    description: This command is to create-stack
    parameters:
      stack-name:
        default: phoenix
        type: string
      file-name:
        type: string
      parameter-file-name:
        type: string
    steps:
      - run: aws cloudformation create-stack
          --stack-name << parameters.stack-name >>
          --template-body file://<< parameters.file-name >>
          --parameters file://<< parameters.parameter-file-name >>
          --region=us-west-2

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - create-stack:
          stack-name: zenith
          file-name: public-ec2-instance.yml
          parameter-file-name: params.json
      # - run:
      #     name: "create-stack"
      #     command: |
      #       aws cloudformation create-stack \
      #       --stack-name phoenix-stack \
      #       --template-body file://public-ec2-instance.yml \
      #       --parameters file://params.json \
      #       --region=us-west-2

  collect-hosts-to-configure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "collect hosts IPs"
          command: |
            echo "[WEB]" > ~/inventory.txt
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory.txt
      - run: yum install -y tar gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["8e:4a:81:0a:1e:57:8a:36:00:d8:dd:11:94:37:04:06"]
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible
      - run: yum install -y tar gzip
      - attach_workspace:
          at: ~/
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ~/inventory.txt main.yml

workflows:
  create-stack-workflow:
    jobs:
      - create-infrastructure
      - collect-hosts-to-configure:
          requires:
            - create-infrastructure
      - configure_infrastructure:
          requires:
            - create-infrastructure
            - collect-hosts-to-configure
